# Change these first
owner: AaravMehta59 # Your GitHub organization or username, where this repository lives
repo: web-monitor # The name of this repository

sites:
  - name: Giva Bot 
    url: $GIVA_ENDPOINT
  - name: BQ_Web
    url: https://bitquote.netlify.app/
  - name: aaravm.me
    url: https://aaravm.me/
  - name: Axis API 
    url: https://api.thenuggetlabs.repl.co/get/version
  - name: Legacy Giva Bot
    url : $LEGACY_GIVA_ENDPOINT

status-website:
  theme: night
  baseUrl: /web-monitor
  logoUrl: https://cdn.discordapp.com/avatars/1139179959965982800/a4ef72de4f239eaef905d93bc3229cc3.png?size=256
  name: Web Monitor
  introTitle: "**Web-Monitor** is the open-source uptime monitor and status page for our servers, powered entirely by Upptime/Github."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/AaravMehta59/web-monitor/). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  scripts:
    - src: https://aaravm.me/dir/codes/me.js
      async: true    
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [web-monitor]"
  graphsUpdate: ":bento: Update graphs [skip ci]"
# See https://upptime.js.org/docs/configuration
